// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAZH_88y3qSMym2ZrNo2lbVTymePp51yNM',
//     appId: '1:124351345456:web:4cc24f828411c2bacf4ef5',
//     messagingSenderId: '124351345456',
//     projectId: 'gd-building',
//     authDomain: 'gd-building.firebaseapp.com',
//     storageBucket: 'gd-building.appspot.com',
//     measurementId: 'G-ET44P0JMDX',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBwa6RxIkgY0uR9PgceeAXbzc4lAaqwlRw',
//     appId: '1:124351345456:android:8efe53bb5f783b0ecf4ef5',
//     messagingSenderId: '124351345456',
//     projectId: 'gd-building',
//     storageBucket: 'gd-building.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAnyatN1v8VCMQ9rOdB0edwe-wlhB6ts8Q',
//     appId: '1:124351345456:ios:abb6326536f9127acf4ef5',
//     messagingSenderId: '124351345456',
//     projectId: 'gd-building',
//     storageBucket: 'gd-building.appspot.com',
//     iosBundleId: 'com.bwchennai.red',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAnyatN1v8VCMQ9rOdB0edwe-wlhB6ts8Q',
//     appId: '1:124351345456:ios:a58ae1c6915efeb5cf4ef5',
//     messagingSenderId: '124351345456',
//     projectId: 'gd-building',
//     storageBucket: 'gd-building.appspot.com',
//     iosBundleId: 'com.example.red',
//   );
// }
